# Generated by Django 2.2.5 on 2019-10-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Number', models.IntegerField(max_length=100)),
                ('Comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=10)),
                ('SecondType', models.CharField(max_length=10)),
                ('Number', models.IntegerField(max_length=100)),
                ('Comment', models.TextField()),
            ],
        ),
    ]
