# Generated by Django 2.2.5 on 2019-10-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='Number',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Comment',
            field=models.TextField(null=True),
        ),
    ]
