# Generated by Django 2.2.5 on 2019-10-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20191013_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='SecondType',
        ),
    ]
