# Generated by Django 2.2.5 on 2019-10-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_equipments_secondtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='equipments',
        ),
    ]
