# Generated by Django 2.2.5 on 2019-10-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20191013_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类名')),
                ('content', models.TextField(verbose_name='清单（请用逗号隔开）')),
                ('remark', models.TextField(blank=True, verbose_name='清单')),
            ],
        ),
        migrations.DeleteModel(
            name='equipment',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
