# Generated by Django 2.2.5 on 2019-10-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20191015_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='content',
        ),
        migrations.AddField(
            model_name='tool',
            name='free_tools',
            field=models.TextField(default='', verbose_name='可用工具（请用逗号隔开）'),
        ),
        migrations.AddField(
            model_name='tool',
            name='used_tools',
            field=models.TextField(blank=True, default='', verbose_name='已使用工具（请用逗号隔开）'),
        ),
    ]
