# Generated by Django 2.2.5 on 2019-10-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20191015_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='申请人')),
                ('tools', models.TextField(verbose_name='租借设备')),
                ('regard', models.TextField(verbose_name='租借事由')),
                ('phone', models.IntegerField(max_length=11, verbose_name='电话号码')),
                ('date', models.DateField(verbose_name='借出日期')),
            ],
        ),
        migrations.AlterField(
            model_name='tool',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
    ]
