# Generated by Django 2.2.5 on 2019-10-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20191016_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='申请人')),
                ('tools', models.TextField(verbose_name='借用设备')),
                ('regard', models.TextField(verbose_name='借用事由')),
                ('phone', models.IntegerField(max_length=11, verbose_name='电话号码')),
                ('rent_date', models.DateField(verbose_name='借出日期')),
                ('return_date', models.DateField(verbose_name='归还日期')),
            ],
        ),
        migrations.AlterField(
            model_name='rentorder',
            name='regard',
            field=models.TextField(verbose_name='借用事由'),
        ),
        migrations.AlterField(
            model_name='rentorder',
            name='tools',
            field=models.TextField(verbose_name='借用设备'),
        ),
    ]
