# Generated by Django 2.2.5 on 2019-10-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20191018_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentorder',
            name='return_date',
            field=models.DateField(blank=True, default='0000-00-00', verbose_name='归还日期'),
        ),
    ]
