# Generated by Django 2.2.5 on 2019-10-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20191018_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentorder',
            name='return_date',
            field=models.DateField(auto_now=True, verbose_name='归还日期'),
        ),
    ]
