# Generated by Django 2.2.6 on 2019-10-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_remove_rentorder_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentorder',
            options={'verbose_name_plural': '借用订单管理'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name_plural': '设备管理'},
        ),
    ]
